SET IDENTITY_INSERT [dbo].[Lyrics] ON
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (1002, N'Shakira ', N'Whenever, Wherever', N'Lucky that my breasts are small and humble, so you don''t confuse them with mountains.', 1)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (1005, N'Ke$ha', N'Blah Blah Blah', N'Zip your lips like a padlock.', -1)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (1006, N'The Killers', N'Human', N'Are we human? Or are we dancer?', 2)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (1007, N'Warren Zevon', N'Werewolves of London', N'I saw a werewolf drinking a piña colada at Trader Vic''s and his hair was perfect.', 1)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (1008, N'The Eagles', N'Hotel California', N'So I called up the captain, Please bring me my wine, he said, "We haven’t had that spirit here since 1969".', -1)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (1010, N'Big Sean', N'All Me', N'I’m the type to have a bullet-proof condom and still gotta pull out, But that’s just me and I ain’t perfect.', NULL)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (1012, N'Bob Dylan', N'You’re A Big Girl Now', N'Time is a jet plane, it moves too fast.', NULL)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (2002, N'Ayo', N'Många som väntar', N'Folk kommer ihåg mig som tomten i en gran.', 4)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (3002, N'Des''Ree', N'Life', N'I don''t want to see a ghost, It''s a sight that I fear most
I''d rather have a piece of toast and watch the evening news.', 2)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (4002, N'Oasis', N'Champagne Supernova', N'Slowly walking down the hall, faster than a cannonball.', 1)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (4003, N'Michael Jackson', N'Earth Song', N'What about elephants? Have we lost their trust?', NULL)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (4004, N'L.F.O.', N'Summer Girls', N'New Kids on the Block had a bunch of hits, Chinese food makes me sick.', 1)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (4005, N'Van Halen', N'Why Can’t This Be Love?', N'Only time will tell if we stand the test of time.', 1)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (4006, N'Lil B', N'Wonton Soup', N'Bitches suck my dick because I look like J.K. Rowling.', 3)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (4007, N'Drake', N'What’s My Name?', N'The square root of 69 is 8 something, right? / Cause I’ve been tryna work it out.', 1)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (4008, N'2 Chainz', N'Birthday Song', N'She got a big booty so I call her Big Booty.', 2)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (4009, N'Jimmy Webb', N'MacArthur Park', N'Someone left the cake out in the rain / I don’t think that I can take it / Cause it took so long to bake it / And I’ll never have that recipe again.', -1)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (4010, N'Hilary Duff', N'So Yesterday', N'If the light is off, then it isn’t on.', NULL)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (4011, N'Ariana Grande', N'Break Free', N'I only want to die alive.', 1)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (4012, N'Britney Spears', N'Email My Heart', N'Email my heart and say our love will never die.', 2)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (4013, N'Train', N'50 Ways to Say Goodbye', N'Someday I’ll find a love like yours/ she’ll think I’m superman not super minivan/ how could you leave on Yom Kippur?', 1)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (4014, N'Deep Purple', N'Highway Star', N'She’s got everything – like a moving mouth, body control and everything.', 2)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (4015, N'Sublime', N'What I Got', N'I got a Dalmatian, I can still get high.', 3)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (4016, N'Paul Anka', N'(You’re) Having My Baby', N'Havin’ my baby, what a lovely way of sayin’ what you’re thinkin’ of me.', 1)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (4017, N'Juelz Santana', N'Black Republicans', N'Rock star, flyer than an ostrich.', 2)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (4019, N'Warren G', N'What’s Next', N'I say what’s next? What’s next? What’s N-X-E-T?', NULL)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (4020, N'Lil’ Fame', N'Half and Half', N'First Family will gradually lift that ass up like gravity.', 2)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (4021, N'Chingy', N'Balla Baby', N'I like them black, white, Puerto Rican, or Haitian/Like Japanese, Chinese or even Asian.', NULL)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (4022, N'Nicki Minaj', N'Your Love', N'When I was a geisha, he was a samurai/Somehow I understood him when he spoke Thai.', NULL)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (4023, N'LMFAO', N'Love Lockdown', N'You done broke my heart into a million pieces/I should have seen it coming, wish I had telekinesis.', 1)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (4024, N'Insane Clown Posse', N'Miracles', N'Water, fire, air and dirt/Fuckin’ magnets, how do they work?/And I don’t want to talk to a scientist/Y’all motherfuckers lying and gettin’ me pissed.', 2)
INSERT INTO [dbo].[Lyrics] ([Id], [Artist], [Song], [Lyric], [Rating]) VALUES (5002, N'Thin Lizzy', N'Jailbreak', N'Tonight there''s gonna be a jailbreak, somewhere in this town.', NULL)
SET IDENTITY_INSERT [dbo].[Lyrics] OFF
